// This file was generated by counterfeiter
package fakes

import "sync"

type FakeconsulRPCClient struct {
	StatsStub        func() (map[string]map[string]string, error)
	statsMutex       sync.RWMutex
	statsArgsForCall []struct{}
	statsReturns     struct {
		result1 map[string]map[string]string
		result2 error
	}
}

func (fake *FakeconsulRPCClient) Stats() (map[string]map[string]string, error) {
	fake.statsMutex.Lock()
	fake.statsArgsForCall = append(fake.statsArgsForCall, struct{}{})
	fake.statsMutex.Unlock()
	if fake.StatsStub != nil {
		return fake.StatsStub()
	} else {
		return fake.statsReturns.result1, fake.statsReturns.result2
	}
}

func (fake *FakeconsulRPCClient) StatsCallCount() int {
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	return len(fake.statsArgsForCall)
}

func (fake *FakeconsulRPCClient) StatsReturns(result1 map[string]map[string]string, result2 error) {
	fake.StatsStub = nil
	fake.statsReturns = struct {
		result1 map[string]map[string]string
		result2 error
	}{result1, result2}
}

// var _ confab.consulRPCClient = new(FakeconsulRPCClient)
