#!/bin/bash -eu

function main() {
  if [[ -n "$@" ]]; then
    ginkgo "$@"
  else
    local dir
    dir="$(cd "$(dirname "${0}")/.." && pwd)"
    ginkgo \
		-r \
		-randomizeAllSpecs \
		-randomizeSuites \
		"${dir}"
  fi
}

main "$@"
