#!/bin/bash

set -e

manifest_generation=$(dirname $0)/../manifest-generation

function usage() {
  >&2 echo "    Usage:
    $0 /path/to/stub/director-uuid.yml \\
       /path/to/stub/instance-count-overrides.yml \\
       /path/to/stub/persistent-disk-overrides.yml \\
       /path/to/stub/iaas-settings.yml \\
       /path/to/stub/turbulence-properties.yml \\
       [/path/to/stub/name-overrides.yml]

    Ex:
    $0 ~/deployments/bosh-lite/director.yml \\
       manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \\
       manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \\
       manifest-generation/bosh-lite-stubs/iaas-settings-turbulence.yml \\
       manigest-generation/bosh-lite-stubs/turbulence/property-settings.yml
"
  exit 1
}

director_uuid=$1
instance_counts=$2
persistent_disk=$3
iaas_settings=$4
turbulence_settings=$5
name_overrides=$6


if [ ! -f "${director_uuid}" ]; then
  >&2 echo "Director UUID stub '${director_uuid}' is not a regular file"
  usage
fi

if [ ! -f "${instance_counts}" ]; then
  >&2 echo "Instance Count Overrides stub '${instance_counts}' is not a regular file"
  usage
fi

if [ ! -f "${persistent_disk}" ]; then
  >&2 echo "Persistent Disk Overrides stub '${persistent_disk}' is not a regular file"
  usage
fi

if [ ! -f "${iaas_settings}" ]; then
  >&2 echo "IaaS Setting stub '${iaas_settings}' is not a regular file"
  usage
fi

if [ ! -f "${turbulence_settings}" ]; then
  >&2 echo "Turbulence Setting stub '${turbulence_settings}' is not a regular file"
  usage
fi

if [ ! -z "$7" ]; then
  >&2 echo "Too many arguments"
  usage
fi

tmpdir=$(mktemp -d /tmp/consul-manifest.XXXXX)

if [ ! -z "${name_overrides}" ]; then
  spiff merge \
    ${manifest_generation}/turbulence.yml \
    ${instance_counts} \
    ${persistent_disk} \
    ${iaas_settings} \
    ${turbulence_settings} \
    ${name_overrides} \
    > ${tmpdir}/turbulence.yml
else
  spiff merge \
    ${manifest_generation}/turbulence.yml \
    ${instance_counts} \
    ${persistent_disk} \
    ${iaas_settings} \
    ${turbulence_settings} \
    > ${tmpdir}/turbulence.yml
fi

spiff merge \
  ${manifest_generation}/misc-templates/bosh.yml \
  ${director_uuid} \
  ${tmpdir}/turbulence.yml
