#!/bin/bash -eux

function main() {
	local scripts_dir
	scripts_dir=$(cd "$(dirname "${0}")" && pwd)

	local root_dir
	root_dir=$(cd "${scripts_dir}/.." && pwd)

	export GOPATH="${root_dir}:${GOPATH}"
	export PATH="${root_dir}/bin:${PATH}"

	# Bosh-lite manifest generation should always work.
	"${scripts_dir}/../../../scripts/generate-bosh-lite-manifest" > /dev/null

	install_ginkgo "${root_dir}"
	pushd "${root_dir}" > /dev/null
		# Run acceptance tests
		ginkgo \
			-r \
			-race \
			-randomizeAllSpecs \
			-randomizeSuites \
			-skipPackage vendor \
			-slowSpecThreshold 300 \
			"$@"
	popd > /dev/null
}

function install_ginkgo() {
	local dir
	dir="${1}"

	mkdir -p "${dir}/src/github.com/onsi"
	pushd "${dir}/src/github.com/onsi" > /dev/null
		ln -s "${dir}/vendor/github.com/onsi/ginkgo"
		go install github.com/onsi/ginkgo/ginkgo
	popd > /dev/null
	rm "${dir}/src/github.com/onsi/ginkgo"
}

main "$@"
