#!/bin/bash -xu

LOG_DIR=/var/vcap/sys/log/consul_agent
JOB_DIR=/var/vcap/jobs/consul_agent

exec 3>&1

mkdir -p "${LOG_DIR}"

exec 1>> ${LOG_DIR}/drain.log
exec 2>> ${LOG_DIR}/drain.log

${JOB_DIR}/bin/agent_ctl stop

echo 0 >&3
exit 0
