// This file was generated by counterfeiter
package main

import (
	"sync"

	"github.com/hashicorp/consul/command/agent"
	"github.com/hashicorp/consul/consul/structs"
	"github.com/hashicorp/serf/serf"
)

type FakeAgentBackend struct {
	ForceLeaveStub        func(string) error
	forceLeaveMutex       sync.RWMutex
	forceLeaveArgsForCall []struct {
		arg1 string
	}
	forceLeaveReturns struct {
		result1 error
	}
	JoinWANStub        func([]string) (int, error)
	joinWANMutex       sync.RWMutex
	joinWANArgsForCall []struct {
		arg1 []string
	}
	joinWANReturns struct {
		result1 int
		result2 error
	}
	JoinLANStub        func([]string) (int, error)
	joinLANMutex       sync.RWMutex
	joinLANArgsForCall []struct {
		arg1 []string
	}
	joinLANReturns struct {
		result1 int
		result2 error
	}
	LANMembersStub        func() []serf.Member
	lANMembersMutex       sync.RWMutex
	lANMembersArgsForCall []struct{}
	lANMembersReturns     struct {
		result1 []serf.Member
	}
	WANMembersStub        func() []serf.Member
	wANMembersMutex       sync.RWMutex
	wANMembersArgsForCall []struct{}
	wANMembersReturns     struct {
		result1 []serf.Member
	}
	LeaveStub        func() error
	leaveMutex       sync.RWMutex
	leaveArgsForCall []struct{}
	leaveReturns     struct {
		result1 error
	}
	ShutdownStub        func() error
	shutdownMutex       sync.RWMutex
	shutdownArgsForCall []struct{}
	shutdownReturns     struct {
		result1 error
	}
	StatsStub        func() map[string]map[string]string
	statsMutex       sync.RWMutex
	statsArgsForCall []struct{}
	statsReturns     struct {
		result1 map[string]map[string]string
	}
	ListKeysStub        func(string) (*structs.KeyringResponses, error)
	listKeysMutex       sync.RWMutex
	listKeysArgsForCall []struct {
		arg1 string
	}
	listKeysReturns struct {
		result1 *structs.KeyringResponses
		result2 error
	}
	InstallKeyStub        func(string, string) (*structs.KeyringResponses, error)
	installKeyMutex       sync.RWMutex
	installKeyArgsForCall []struct {
		arg1 string
		arg2 string
	}
	installKeyReturns struct {
		result1 *structs.KeyringResponses
		result2 error
	}
	UseKeyStub        func(string, string) (*structs.KeyringResponses, error)
	useKeyMutex       sync.RWMutex
	useKeyArgsForCall []struct {
		arg1 string
		arg2 string
	}
	useKeyReturns struct {
		result1 *structs.KeyringResponses
		result2 error
	}
	RemoveKeyStub        func(string, string) (*structs.KeyringResponses, error)
	removeKeyMutex       sync.RWMutex
	removeKeyArgsForCall []struct {
		arg1 string
		arg2 string
	}
	removeKeyReturns struct {
		result1 *structs.KeyringResponses
		result2 error
	}
}

func (fake *FakeAgentBackend) ForceLeave(arg1 string) error {
	fake.forceLeaveMutex.Lock()
	fake.forceLeaveArgsForCall = append(fake.forceLeaveArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.forceLeaveMutex.Unlock()
	if fake.ForceLeaveStub != nil {
		return fake.ForceLeaveStub(arg1)
	} else {
		return fake.forceLeaveReturns.result1
	}
}

func (fake *FakeAgentBackend) ForceLeaveCallCount() int {
	fake.forceLeaveMutex.RLock()
	defer fake.forceLeaveMutex.RUnlock()
	return len(fake.forceLeaveArgsForCall)
}

func (fake *FakeAgentBackend) ForceLeaveArgsForCall(i int) string {
	fake.forceLeaveMutex.RLock()
	defer fake.forceLeaveMutex.RUnlock()
	return fake.forceLeaveArgsForCall[i].arg1
}

func (fake *FakeAgentBackend) ForceLeaveReturns(result1 error) {
	fake.ForceLeaveStub = nil
	fake.forceLeaveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentBackend) JoinWAN(arg1 []string) (int, error) {
	fake.joinWANMutex.Lock()
	fake.joinWANArgsForCall = append(fake.joinWANArgsForCall, struct {
		arg1 []string
	}{arg1})
	fake.joinWANMutex.Unlock()
	if fake.JoinWANStub != nil {
		return fake.JoinWANStub(arg1)
	} else {
		return fake.joinWANReturns.result1, fake.joinWANReturns.result2
	}
}

func (fake *FakeAgentBackend) JoinWANCallCount() int {
	fake.joinWANMutex.RLock()
	defer fake.joinWANMutex.RUnlock()
	return len(fake.joinWANArgsForCall)
}

func (fake *FakeAgentBackend) JoinWANArgsForCall(i int) []string {
	fake.joinWANMutex.RLock()
	defer fake.joinWANMutex.RUnlock()
	return fake.joinWANArgsForCall[i].arg1
}

func (fake *FakeAgentBackend) JoinWANReturns(result1 int, result2 error) {
	fake.JoinWANStub = nil
	fake.joinWANReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentBackend) JoinLAN(arg1 []string) (int, error) {
	fake.joinLANMutex.Lock()
	fake.joinLANArgsForCall = append(fake.joinLANArgsForCall, struct {
		arg1 []string
	}{arg1})
	fake.joinLANMutex.Unlock()
	if fake.JoinLANStub != nil {
		return fake.JoinLANStub(arg1)
	} else {
		return fake.joinLANReturns.result1, fake.joinLANReturns.result2
	}
}

func (fake *FakeAgentBackend) JoinLANCallCount() int {
	fake.joinLANMutex.RLock()
	defer fake.joinLANMutex.RUnlock()
	return len(fake.joinLANArgsForCall)
}

func (fake *FakeAgentBackend) JoinLANArgsForCall(i int) []string {
	fake.joinLANMutex.RLock()
	defer fake.joinLANMutex.RUnlock()
	return fake.joinLANArgsForCall[i].arg1
}

func (fake *FakeAgentBackend) JoinLANReturns(result1 int, result2 error) {
	fake.JoinLANStub = nil
	fake.joinLANReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentBackend) LANMembers() []serf.Member {
	fake.lANMembersMutex.Lock()
	fake.lANMembersArgsForCall = append(fake.lANMembersArgsForCall, struct{}{})
	fake.lANMembersMutex.Unlock()
	if fake.LANMembersStub != nil {
		return fake.LANMembersStub()
	} else {
		return fake.lANMembersReturns.result1
	}
}

func (fake *FakeAgentBackend) LANMembersCallCount() int {
	fake.lANMembersMutex.RLock()
	defer fake.lANMembersMutex.RUnlock()
	return len(fake.lANMembersArgsForCall)
}

func (fake *FakeAgentBackend) LANMembersReturns(result1 []serf.Member) {
	fake.LANMembersStub = nil
	fake.lANMembersReturns = struct {
		result1 []serf.Member
	}{result1}
}

func (fake *FakeAgentBackend) WANMembers() []serf.Member {
	fake.wANMembersMutex.Lock()
	fake.wANMembersArgsForCall = append(fake.wANMembersArgsForCall, struct{}{})
	fake.wANMembersMutex.Unlock()
	if fake.WANMembersStub != nil {
		return fake.WANMembersStub()
	} else {
		return fake.wANMembersReturns.result1
	}
}

func (fake *FakeAgentBackend) WANMembersCallCount() int {
	fake.wANMembersMutex.RLock()
	defer fake.wANMembersMutex.RUnlock()
	return len(fake.wANMembersArgsForCall)
}

func (fake *FakeAgentBackend) WANMembersReturns(result1 []serf.Member) {
	fake.WANMembersStub = nil
	fake.wANMembersReturns = struct {
		result1 []serf.Member
	}{result1}
}

func (fake *FakeAgentBackend) Leave() error {
	fake.leaveMutex.Lock()
	fake.leaveArgsForCall = append(fake.leaveArgsForCall, struct{}{})
	fake.leaveMutex.Unlock()
	if fake.LeaveStub != nil {
		return fake.LeaveStub()
	} else {
		return fake.leaveReturns.result1
	}
}

func (fake *FakeAgentBackend) LeaveCallCount() int {
	fake.leaveMutex.RLock()
	defer fake.leaveMutex.RUnlock()
	return len(fake.leaveArgsForCall)
}

func (fake *FakeAgentBackend) LeaveReturns(result1 error) {
	fake.LeaveStub = nil
	fake.leaveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentBackend) Shutdown() error {
	fake.shutdownMutex.Lock()
	fake.shutdownArgsForCall = append(fake.shutdownArgsForCall, struct{}{})
	fake.shutdownMutex.Unlock()
	if fake.ShutdownStub != nil {
		return fake.ShutdownStub()
	} else {
		return fake.shutdownReturns.result1
	}
}

func (fake *FakeAgentBackend) ShutdownCallCount() int {
	fake.shutdownMutex.RLock()
	defer fake.shutdownMutex.RUnlock()
	return len(fake.shutdownArgsForCall)
}

func (fake *FakeAgentBackend) ShutdownReturns(result1 error) {
	fake.ShutdownStub = nil
	fake.shutdownReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentBackend) Stats() map[string]map[string]string {
	fake.statsMutex.Lock()
	fake.statsArgsForCall = append(fake.statsArgsForCall, struct{}{})
	fake.statsMutex.Unlock()
	if fake.StatsStub != nil {
		return fake.StatsStub()
	} else {
		return fake.statsReturns.result1
	}
}

func (fake *FakeAgentBackend) StatsCallCount() int {
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	return len(fake.statsArgsForCall)
}

func (fake *FakeAgentBackend) StatsReturns(result1 map[string]map[string]string) {
	fake.StatsStub = nil
	fake.statsReturns = struct {
		result1 map[string]map[string]string
	}{result1}
}

func (fake *FakeAgentBackend) ListKeys(arg1 string) (*structs.KeyringResponses, error) {
	fake.listKeysMutex.Lock()
	fake.listKeysArgsForCall = append(fake.listKeysArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.listKeysMutex.Unlock()
	if fake.ListKeysStub != nil {
		return fake.ListKeysStub(arg1)
	} else {
		return fake.listKeysReturns.result1, fake.listKeysReturns.result2
	}
}

func (fake *FakeAgentBackend) ListKeysCallCount() int {
	fake.listKeysMutex.RLock()
	defer fake.listKeysMutex.RUnlock()
	return len(fake.listKeysArgsForCall)
}

func (fake *FakeAgentBackend) ListKeysArgsForCall(i int) string {
	fake.listKeysMutex.RLock()
	defer fake.listKeysMutex.RUnlock()
	return fake.listKeysArgsForCall[i].arg1
}

func (fake *FakeAgentBackend) ListKeysReturns(result1 *structs.KeyringResponses, result2 error) {
	fake.ListKeysStub = nil
	fake.listKeysReturns = struct {
		result1 *structs.KeyringResponses
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentBackend) InstallKey(arg1 string, arg2 string) (*structs.KeyringResponses, error) {
	fake.installKeyMutex.Lock()
	fake.installKeyArgsForCall = append(fake.installKeyArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.installKeyMutex.Unlock()
	if fake.InstallKeyStub != nil {
		return fake.InstallKeyStub(arg1, arg2)
	} else {
		return fake.installKeyReturns.result1, fake.installKeyReturns.result2
	}
}

func (fake *FakeAgentBackend) InstallKeyCallCount() int {
	fake.installKeyMutex.RLock()
	defer fake.installKeyMutex.RUnlock()
	return len(fake.installKeyArgsForCall)
}

func (fake *FakeAgentBackend) InstallKeyArgsForCall(i int) (string, string) {
	fake.installKeyMutex.RLock()
	defer fake.installKeyMutex.RUnlock()
	return fake.installKeyArgsForCall[i].arg1, fake.installKeyArgsForCall[i].arg2
}

func (fake *FakeAgentBackend) InstallKeyReturns(result1 *structs.KeyringResponses, result2 error) {
	fake.InstallKeyStub = nil
	fake.installKeyReturns = struct {
		result1 *structs.KeyringResponses
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentBackend) UseKey(arg1 string, arg2 string) (*structs.KeyringResponses, error) {
	fake.useKeyMutex.Lock()
	fake.useKeyArgsForCall = append(fake.useKeyArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.useKeyMutex.Unlock()
	if fake.UseKeyStub != nil {
		return fake.UseKeyStub(arg1, arg2)
	} else {
		return fake.useKeyReturns.result1, fake.useKeyReturns.result2
	}
}

func (fake *FakeAgentBackend) UseKeyCallCount() int {
	fake.useKeyMutex.RLock()
	defer fake.useKeyMutex.RUnlock()
	return len(fake.useKeyArgsForCall)
}

func (fake *FakeAgentBackend) UseKeyArgsForCall(i int) (string, string) {
	fake.useKeyMutex.RLock()
	defer fake.useKeyMutex.RUnlock()
	return fake.useKeyArgsForCall[i].arg1, fake.useKeyArgsForCall[i].arg2
}

func (fake *FakeAgentBackend) UseKeyReturns(result1 *structs.KeyringResponses, result2 error) {
	fake.UseKeyStub = nil
	fake.useKeyReturns = struct {
		result1 *structs.KeyringResponses
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentBackend) RemoveKey(arg1 string, arg2 string) (*structs.KeyringResponses, error) {
	fake.removeKeyMutex.Lock()
	fake.removeKeyArgsForCall = append(fake.removeKeyArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.removeKeyMutex.Unlock()
	if fake.RemoveKeyStub != nil {
		return fake.RemoveKeyStub(arg1, arg2)
	} else {
		return fake.removeKeyReturns.result1, fake.removeKeyReturns.result2
	}
}

func (fake *FakeAgentBackend) RemoveKeyCallCount() int {
	fake.removeKeyMutex.RLock()
	defer fake.removeKeyMutex.RUnlock()
	return len(fake.removeKeyArgsForCall)
}

func (fake *FakeAgentBackend) RemoveKeyArgsForCall(i int) (string, string) {
	fake.removeKeyMutex.RLock()
	defer fake.removeKeyMutex.RUnlock()
	return fake.removeKeyArgsForCall[i].arg1, fake.removeKeyArgsForCall[i].arg2
}

func (fake *FakeAgentBackend) RemoveKeyReturns(result1 *structs.KeyringResponses, result2 error) {
	fake.RemoveKeyStub = nil
	fake.removeKeyReturns = struct {
		result1 *structs.KeyringResponses
		result2 error
	}{result1, result2}
}

var _ agent.AgentBackend = new(FakeAgentBackend)
