#!/bin/bash

set -e

manifest_generation=$(dirname $0)/../manifest-generation

function usage() {
  >&2 echo "    Usage:
    $0 /path/to/stub/director-uuid.yml \\
       /path/to/stub/instance-count-overrides.yml \\
       /path/to/stub/persistent-disk-overrides.yml \\
       /path/to/stub/iaas-settings.yml \\
       /path/to/stub/properties \\
       [/path/to/stub/name-overrides.yml]

    Ex:
    $0 ~/deployments/bosh-lite/director.yml \\
       manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \\
       manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \\
       manifest-generation/bosh-lite-stubs/property-overrides.yml \\
       manifest-generation/bosh-lite-stubs/iaas-settings.yml
"
  exit 1
}

director_uuid=$1
instance_counts=$2
persistent_disk=$3
iaas_settings=$4
consul_properties=$5
name_overrides=$6

if [ -z "${iaas_settings}" ]; then
  >&2 echo "Not enough arguments"
  usage
fi

if [ ! -z "$7" ]; then
  >&2 echo "Too many arguments"
  usage
fi

if [ ! -e "${director_uuid}" ] || [ -d "${director_uuid}" ]; then
  >&2 echo "Director UUID stub '${director_uuid}' is not a regular file"
  usage
fi

if [ ! -f "${instance_counts}" ]; then
  >&2 echo "Instance Count Overrides stub '${instance_counts}' is not a regular file"
  usage
fi

if [ ! -f "${persistent_disk}" ]; then
  >&2 echo "Persistent Disk Overrides stub '${persistent_disk}' is not a regular file"
  usage
fi

if [ ! -f "${iaas_settings}" ]; then
  >&2 echo "IaaS Setting stub '${iaas_settings}' is not a regular file"
  usage
fi

if [ ! -f "${consul_properties}" ]; then
  >&2 echo "Consul Properties stub '${consul_properties}' is not a regular file"
  usage
fi

tmpdir=$(mktemp -d /tmp/consul-manifest.XXXXX)

if [ ! -z "${name_overrides}" ]; then
  spiff merge \
    ${manifest_generation}/consul.yml \
    ${instance_counts} \
    ${persistent_disk} \
    ${iaas_settings} \
    ${consul_properties} \
    ${name_overrides} \
    > ${tmpdir}/consul.yml
else
  spiff merge \
    ${manifest_generation}/consul.yml \
    ${instance_counts} \
    ${persistent_disk} \
    ${iaas_settings} \
    ${consul_properties} \
    > ${tmpdir}/consul.yml
fi

spiff merge \
  ${manifest_generation}/misc-templates/bosh.yml \
  ${director_uuid} \
  ${tmpdir}/consul.yml
