#!/bin/bash

set -eux

root_dir=$(cd "$(dirname "${0}")/.." && pwd)

stubs_dir="${root_dir}/manifest-generation/bosh-lite-stubs"

DIRECTOR_UUID=$(bosh status --uuid)
export DIRECTOR_UUID

pushd "${root_dir}"
  mkdir -p bosh-lite

  ./scripts/generate-consul-deployment-manifest \
    <(echo "director_uuid: ${DIRECTOR_UUID}") \
    "${stubs_dir}/instance-count-overrides.yml" \
    "${stubs_dir}/persistent-disk-overrides.yml" \
    "${stubs_dir}/iaas-settings-consul.yml" \
    "${stubs_dir}/property-overrides.yml" > bosh-lite/consul.yml

  bosh deployment bosh-lite/consul.yml
popd
