#!/bin/sh

set -ex

root_dir=$(cd $(dirname $0)/.. && pwd)

echo $root_dir

export GOPATH=$root_dir:$GOPATH
export PATH=$root_dir/bin:$PATH

# install ginkgo
go install -v github.com/onsi/ginkgo/ginkgo

ginkgo -r src/acceptance-tests
