#!/bin/sh

set -eux

my_dir=$(cd "$(dirname "${0}")" && pwd)
root_dir=$(cd "${my_dir}/.." && pwd)

export GOPATH="${root_dir}:${GOPATH}"
export PATH="${root_dir}/bin:${PATH}"

# Bosh-lite manifest generation should always work.
"${my_dir}/generate-bosh-lite-manifest" > /dev/null

# install ginkgo
go install -v github.com/onsi/ginkgo/ginkgo

# Run acceptance tests
ginkgo \
    -r \
    -race \
    -randomizeAllSpecs \
    -randomizeSuites \
    "$@"
