#!/bin/bash -eux

consul_release_version="99999+dev.${RANDOM}"
warden_cpi_version="28"
turbulence_version="0.4"

function main() {
	local scripts_dir
	scripts_dir=$(cd "$(dirname "${0}")" && pwd)

	upload_releases "${scripts_dir}"
	bash -c "${scripts_dir}/../src/acceptance-tests/scripts/test $@"
}

function upload_releases() {
	local scripts_dir
	scripts_dir="${1}"

	pushd "${scripts_dir}/.." > /dev/null
		bosh create release --force --version "${consul_release_version}"
		bosh upload release
	popd > /dev/null

	bosh upload release "http://bosh.io/d/github.com/cppforlife/bosh-warden-cpi-release?v=${warden_cpi_version}" --skip-if-exists
	bosh upload release "http://bosh.io/d/github.com/cppforlife/turbulence-release?v=${turbulence_version}" --skip-if-exists
}

function cleanup_releases() {
	bosh -n delete release turbulence "${turbulence_version}"
	bosh -n delete release bosh-warden-cpi "${warden_cpi_version}"
	bosh -n delete release consul "${consul_release_version}"
}

trap cleanup_releases EXIT
main "$@"
